
[target.thumbv7m-none-eabi]
runner = "probe-rs run --chip STM32F103RB"

rustflags = [
    "-C", "link-arg=-Tlink.x",
    # If you run into problems with LLD, switch to the GNU linker by commenting out
    # this line
    # "-C", "linker=arm-none-eabi-ld",
    # If you need to link to pre-compiled C libraries provided by a C toolchain,
    # use GCC as the linker by commenting out both lines above and then
    # uncommenting the three lines below
    # "-C", "linker=arm-none-eabi-gcc",
    # "-C", "link-arg=-Wl,-Tlink.x",
    # "-C", "link-arg=-nostartfiles",
]

[build]
target = "thumbv7m-none-eabi"
